Starting inference with Python: Python 3.9.21
Traceback (most recent call last):
  File "/usr/bin/code/infer.py", line 11, in <module>
    import torch
  File "/usr/local/lib64/python3.11/site-packages/torch/__init__.py", line 237, in <module>
    from torch._C import *  # noqa: F403
    ^^^^^^^^^^^^^^^^^^^^^^
ImportError: libcudnn.so.8: cannot open shared object file: No such file or directory
Error: Python inference script failed.
